import React from "react";


const ChallengeQuestion = (props) => {
   return (
     <>
       <div className="question-text-box">
         <h1>Challenge Question</h1>
         <p>
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE 
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
           QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE QUESTIONS WILL BE HERE
         </p>
       </div>
     </>
   );
};

export default ChallengeQuestion;
