version: '3'
services: 
  server:
    build: ./server
    ports:
      - 5000:5000
    environment: 
      SECRET_OR_KEY: ${SECRET_OR_KEY}
      MONGO_URI: ${MONGO_URI}
  client:
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
