version: '3'
services: 
  server:
    build: ./server
    depends_on: 
      - redis
    ports:
      - 5000:5000
    environment: 
      NODE_ENV: production
      SECRET_OR_KEY: ${SECRET_OR_KEY}
      MONGO_URI: ${MONGO_URI}
      REDIS_URI: redis
      DOCKERIZED: 'true'
      
  client:
    build: ./client
    depends_on: 
      - server
    ports:
      - 3000:3000
    environment: 
      NODE_ENV: production
      PRODUCTION_URI: http://client:3000
    stdin_open: true

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379