version: '3'
services: 
  fake-gcp:
    build: ./fake-gcp
    ports:
      - 8000:8000
    environment:
      PORT: 8000
    volumes:
      - ./fake-gcp:/usr/src/app
    command: npm run dev

  server:
    build: ./server
    depends_on: 
      - redis
    ports:
      - 5000:5000
    environment: 
      NODE_ENV: development
      SECRET_OR_KEY: ${SECRET_OR_KEY}
      PRODUCTION_URI: http://client:3000
      MONGO_URI: ${MONGO_URI}
      REDIS_URI: redis
      DOCKERIZED: 'true'
    volumes: 
      - ./server:/usr/src/app
    command: npm run dev
      
  client:
    build: ./client
    depends_on: 
      - server
    ports:
      - 3000:3000
    environment: 
      NODE_ENV: development
    stdin_open: true
    volumes: 
      - ./client:/usr/src/app

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379
